# Generated by Django 3.0.1 on 2020-01-15 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post_stats', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poststat',
            name='time_spent',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
