# Generated by Django 3.0.1 on 2020-01-15 01:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post_stats', '0002_auto_20200115_0130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poststat',
            name='time_spent',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(86400)]),
        ),
    ]
