# Generated by Django 3.0.1 on 2020-01-31 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('connections', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='connection',
            old_name='created',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='connection',
            old_name='folllowee',
            new_name='followee',
        ),
    ]
